// <auto-generated />
using System;
using MCP_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MCP_DataAccess.Migrations
{
    [DbContext(typeof(ScootDbContext))]
    [Migration("20260903095758_LastTime")]
    partial class LastTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MCP_Domain.Models.App_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phonenumber");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("MCP_Domain.Models.Scooter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Battery_Capacity")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_capacity");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_scooter");

                    b.ToTable("scooter", (string)null);
                });

            modelBuilder.Entity("MCP_Domain.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("App_UserId")
                        .HasColumnType("integer")
                        .HasColumnName("app_userid");

                    b.Property<int>("Cost")
                        .HasColumnType("integer")
                        .HasColumnName("cost");

                    b.Property<int>("Distance")
                        .HasColumnType("integer")
                        .HasColumnName("distance");

                    b.Property<DateTime>("End_Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("ScooterId")
                        .HasColumnType("integer")
                        .HasColumnName("scooterid");

                    b.Property<DateTime>("Start_time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("pk_trip");

                    b.HasIndex("App_UserId")
                        .HasDatabaseName("ix_trip_app_userid");

                    b.HasIndex("ScooterId")
                        .HasDatabaseName("ix_trip_scooterid");

                    b.ToTable("trip", (string)null);
                });

            modelBuilder.Entity("MCP_Domain.Models.UserOnScooter", b =>
                {
                    b.Property<int>("ScooterId")
                        .HasColumnType("integer")
                        .HasColumnName("scooterid");

                    b.Property<int>("App_UserId")
                        .HasColumnType("integer")
                        .HasColumnName("app_userid");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("ScooterId", "App_UserId")
                        .HasName("pk_useronscooter");

                    b.HasIndex("App_UserId")
                        .HasDatabaseName("ix_useronscooter_app_userid");

                    b.ToTable("useronscooter", (string)null);
                });

            modelBuilder.Entity("MCP_Domain.Models.Trip", b =>
                {
                    b.HasOne("MCP_Domain.Models.App_User", "User")
                        .WithMany("Trips")
                        .HasForeignKey("App_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_app_user_app_userid");

                    b.HasOne("MCP_Domain.Models.Scooter", "Scooter")
                        .WithMany("Trips")
                        .HasForeignKey("ScooterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trip_scooter_scooterid");

                    b.Navigation("Scooter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MCP_Domain.Models.UserOnScooter", b =>
                {
                    b.HasOne("MCP_Domain.Models.App_User", "user")
                        .WithMany()
                        .HasForeignKey("App_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_useronscooter_app_user_app_userid");

                    b.HasOne("MCP_Domain.Models.Scooter", "Scooter")
                        .WithMany()
                        .HasForeignKey("ScooterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_useronscooter_scooter_scooterid");

                    b.Navigation("Scooter");

                    b.Navigation("user");
                });

            modelBuilder.Entity("MCP_Domain.Models.App_User", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("MCP_Domain.Models.Scooter", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
